name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Dependencies
        run: pnpm install
      - name: access to secrets
        run: |
          echo "VITE_APP_TOUR_API_KEY=$VITE_APP_TOUR_API_KEY" >> .env
        env:
          VITE_APP_TOUR_API_KEY: ${{secrets.VITE_APP_TOUR_API_KEY}}
      - name: Build
        run: pnpm run build
      - name: Run Test
        run: pnpm run test
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-project-to-vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  Slack:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    steps:
      - name: Set color based on outcome
        if: always()
        id: set-color
        run: |
          if [ "${{ steps.deploy-project-to-vercel.outcome }}" == "success" ]; then
            echo "slack_color=#36a64f" >> $GITHUB_ENV
          else
            echo "slack_color=#FF0000" >> $GITHUB_ENV
          fi
      - name: Slack message
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "attachments": [{
                "pretext": "A new repository has been created",
                "color": "${{ env.slack_color }}",
                "fields": [
                    {
                        "title": "Create repo result ${{ steps.create-repo.outcome }}",
                        "value": "${{ inputs.prefix }}-${{ inputs.name }}",
                        "short": true
                        }
                    ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
